test: &default
  PAYPAL_ENV: sandbox
  PAYPAL_CLIENT_ID: 	 	AQmhbR6XI_OwIqDRIEyFLXLSIxtDEA3AEAq-c3WZ3T1hVEzHoXls0q2vFgLVS1-sPLxpnTDXq5t8nufZ
  PAYPAL_CLIENT_SECRET: 	EC9SxI_lR7SNdHsdW5PhFLXZVr3Ixfx9qHzCgZTZhsWeOyMAJ-f20rG4QaVeXvJ2E1JCG431bfulepOE
  STRIPE_PUBLISHABLE_KEY:	YOUR_CREDENTIAL_HERE
  STRIPE_SECRET_KEY: 	YOUR_CREDENTIAL_HERE
development:
  <<: *default